### ISSUE TITLE
博主您好，请问一下如何将您的这个pyqt程序做好的GUI界面（程序）打包成exe文件呢？

### ISSUE THREAD

**Issue by zxsitu** [xugaoxiang/yolov5-pyqt5#3]
博主您好，看了您的推文和B站视频，觉得代码比较实用，想咨询一下如何将您的这个pyqt程序做好的GUI界面（程序），打包成exe文件呢？可以让外人一点击exe文件就可以检测。可以提供相关的教程吗？十分感谢。

**Comment by xugaoxiang** [comment]
你可以试试pyinstaller或者nuitka

**Comment by zxsitu** [comment]
@xugaoxiang 好的谢谢我试一下，我是windows系统，如果您有时间出一期简单教程就更好了。
